#!/bin/bash
# Reset network interfaces

echo "|----------------------------------------------|"
echo "| Restarting network services... This may take |"
echo "| a few minutes. Please be patient...          |"
echo "|----------------------------------------------|"
echo " "
/etc/init.d/network restart
ifdown enp0s3
ifdown enp0s8
ifup enp0s3
ifup enp0s8
ip addr show | grep "enp0s3"
ip addr show | grep "enp0s8"
echo " "
echo "Repairs complete!"
echo " "
