#!/bin/bash
# Perform a clean install of TossUp 
# !!! This will delete any customizations !!!

echo "Starting install of TossUp from gitHub. This may take a moment..."
systemctl stop httpd
ifdown enp0s3
tar -czvf /root/backup_$(date +"%Y%m%d").tgz -C /var/www html
rm -rf /var/www/html
git clone https://github.com/michaelballen/tossup.git /var/www/html/
ln -s /var/www/html /var/www/html/tossup2
chown -R apache:apache /var/www/html
ifup enp0s3
systemctl start httpd
echo "Install process complete."
