#!/bin/bash
# Restore TossUp from backup file


echo "|----------------------------------------------|"
echo "| Restore TossUp app from backup             |"
echo "|----------------------------------------------|"
echo " "
ls -lah /root/backup_*
read -p "Select backup to restore (type date only in YYYYmmdd format: " backupvar
cd /var/www
tar -xzf /root/backup_${backupvar}.tgz
chown -R apache:apache /var/www/html
cd /root
echo " "
echo "Restore Operation Complete!"
echo " "
