#!/bin/bash
# Startup Script for TossUp VMs

ifdown enp0s3
cd /root
tar -czvf /root/scripts_backup.tgz -C /root install update fix restore startup
git fetch --all
git reset --hard origin/master
chmod 555 install update fix restore startup
ifup enp0s3
