#!/bin/bash
#update TossUp app from GitHub

echo "Starting update. This may take a moment..."
systemctl stop httpd
ifdown enp0s3
tar -czvf /root/backup_$(date +"%Y%m%d").tgz -C /var/www html
cd /var/www/html
#git pull origin master
git fetch --all
git reset --hard origin/master
chown -R apache:apache /var/www/html
cd /root
ifup enp0s3
systemctl start httpd
echo "Update process complete."
